version: "3.9"
services:
  chatgpt-api:
    image: docker.edu-sharing.com/projects/wlo/edu_sharing-projects-wlo-deploy-docker-chatgpt-api:latest
    build:
     context: .
     dockerfile: Dockerfile
    env_file:
     .env
    ports:
     - "8083:80"
